pipeline {
    agent any

    environment{
        DOCKERHUB_CREDENTIALS = credentials('docker-cred')
        IMAGE_TAG="${BUILD_NUMBER}"
    }

    stages{
        stage('checkout'){
            steps{
                git branch: 'main', url : "https://github.com/kriteshsharma/jenkins.git"
            }
        }
        stage('Build Image '){
            steps{
                    sh '''
                    echo 'Building docker image'
                    docker build -t krsharma/python-ci-cd:${BUILD_NUMBER} python-jenkins-argocd-k8s/.
                    '''
            }
        }
        stage('login') {
            steps{
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push Image '){
            steps{
                sh '''
                echo 'Pushing docker image'
                docker push krsharma/python-ci-cd:${BUILD_NUMBER} 
                '''
            }
        }
        stage('Update manifest file'){
            steps{
                scripts{
                    sh '''
                    git config user.name "kriteshsharma"
                    git config user.email "kritesh.bhojnagar@gmail.com"
                    sed -i 's/image: krsharma\\/python-ci-cd:v1/image: krsharma\\/python-ci-cd:${BUILD_NUMBER}/g' python-jenkins-argocd-k8s/deploy/deploy.yaml
                    cat python-jenkins-argocd-k8s/deploy/deploy.yaml
                    git add python-jenkins-argocd-k8s/deploy/deploy.yaml
                    git commit -m "updated manifest file using jenkins ci"
                    git push https://github.com/kriteshsharma/jenkins.git HEAD:main
                    '''
                }
            }
        }
    }
}
